In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

import plotly
from plotly.offline import init_notebook_mode, iplot
import plotly.graph_objs as go
from plotly import tools
from plotly.subplots import make_subplots
import cufflinks
cufflinks.go_offline()
cufflinks.set_config_file(world_readable = True, theme = 'pearl')

from sklearn.feature_extraction.text import CountVectorizer

In [2]:
train = pd.read_csv(r'C:\Users\Louis\Downloads\shopee-sentiment-analysis\train.csv')
test = pd.read_csv(r'C:\Users\Louis\Downloads\shopee-sentiment-analysis\test.csv')
print(train.head(10))
print(test.head(10))

   review_id                                             review  rating
0          0  Ga disappointed neat products .. Meletot Hilsn...       1
1          1    Rdtanya replace broken glass, broken chargernya       1
2          2  Nyesel bngt dsni shopping antecedent photo mes...       1
3          3      Sent a light blue suit goods ga want a refund       1
4          4  Pendants came with dents and scratches on its ...       1
5          5               Dg yg depending being sent in photos       1
6          6                               Hours not a hologram       1
7          7  Shop fraudulent business. we put two lamps, on...       1
8          8                           Well, according to Price       1
9          9  Pictures and names of elise 7154, but the bran...       1
   review_id                                             review
0          1  Great danger, cool, motif and cantik2 jg model...
1          2                   One of the shades don't fit well
2          3    

In [3]:
all_text = '||'.join(train['review'])
print(type(all_text))
print(len(all_text))


<class 'str'>
13235640


In [4]:
chars = list(set(all_text))
print('Total Chars: ', len(chars))

Total Chars:  1197


In [5]:
chars[:10]

['🌪', '💌', '。', '●', '😎', '8', '┬', 'Ü', 'ⓤ', '‧']

In [6]:
cha_count = {}
def append_cha_count(txt):
    for cha in list(set(txt)):
        cha_count[cha] = cha_count.get(cha, 0) + 1
        
train['review'].map(append_cha_count)

print(cha_count)

{'p': 110824, '\u200b': 2375, 'G': 26693, 'e': 139060, 'v': 78550, 'c': 115602, 'f': 73719, 'g': 104891, 'M': 9040, 's': 128098, 't': 136873, 'S': 22262, ' ': 146708, 'r': 133139, 'u': 120635, 'l': 130137, 'y': 120267, 'i': 136538, 'a': 137924, '.': 74694, 'd': 128727, 'o': 134905, 'n': 121065, 'H': 10216, 'k': 72894, 'h': 103321, 'b': 66116, ',': 42301, 'R': 8236, 'j': 12767, 'N': 9949, 'm': 82738, 'x': 29343, 'T': 38185, 'w': 57187, 'q': 51825, 'P': 26804, 'D': 15002, '4': 2632, '2': 8504, 'z': 6418, '1': 5899, '?': 1146, '0': 3250, 'W': 8275, 'V': 8243, 'X': 790, '7': 1091, '5': 2977, 'C': 13942, 'I': 21956, 'L': 7455, 'J': 3052, '!': 6366, 'K': 5282, 'E': 14058, 'A': 19060, 'O': 8880, 'Y': 2285, 'U': 3837, '(': 1777, ':': 2262, '3': 3748, 'B': 14366, '\xa0': 1543, "'": 9513, '😔': 210, '/': 1248, '-': 4853, '💯': 93, '+': 375, '😣': 117, '👎': 164, '8': 1207, 'F': 11439, '🤕': 6, '🙄': 105, '😢': 268, '6': 1362, '²': 221, 'Q': 2724, '🙂': 195, '👌': 682, '’': 498, '=': 146, '&': 844, '😤': 6

In [7]:
df_char = pd.DataFrame()
df_char['char'] = list(cha_count.keys())
df_char['count'] = list(cha_count.values())
df_char = df_char.sort_values('count', ascending = False).reset_index(drop = True)


In [8]:
print(df_char.head(40))
print(df_char.tail(40))

   char   count
0        146708
1     e  139060
2     a  137924
3     t  136873
4     i  136538
5     o  134905
6     r  133139
7     l  130137
8     d  128727
9     s  128098
10    n  121065
11    u  120635
12    y  120267
13    c  115602
14    p  110824
15    g  104891
16    h  103321
17    m   82738
18    v   78550
19    .   74694
20    f   73719
21    k   72894
22    b   66116
23    w   57187
24    q   51825
25    ,   42301
26    T   38185
27    x   29343
28    P   26804
29    G   26693
30    S   22262
31    I   21956
32    A   19060
33    D   15002
34    B   14366
35    E   14058
36    C   13942
37    j   12767
38    F   11439
39    H   10216
     char  count
1157    🇻      1
1158    ◍      1
1159    ꒳      1
1160    ™      1
1161    🔎      1
1162    ﷺ      1
1163    ↔      1
1164    🧀      1
1165    🥫      1
1166    🥡      1
1167    ě      1
1168    𝘥      1
1169    𝘛      1
1170    ̅      1
1171    💧      1
1172    🌂      1
1173    ∩      1
1174    🧶      1
1175    ：      1
1176

In [9]:
df_char['count'].value_counts().head(40)



1      507
2      167
3      100
4       54
5       31
6       29
7       13
9       13
8        9
13       7
10       6
18       6
12       6
15       5
21       5
17       5
11       5
14       5
25       4
19       4
26       4
23       4
35       3
84       3
46       3
40       3
16       3
30       3
97       2
98       2
88       2
268      2
78       2
66       2
61       2
54       2
43       2
49       2
45       2
221      2
Name: count, dtype: int64

In [10]:
df_char.head(10)

char   count
0       146708
1    e  139060
2    a  137924
3    t  136873
4    i  136538
5    o  134905
6    r  133139
7    l  130137
8    d  128727
9    s  128098

In [17]:
df_char.loc[df_char['count'] >= 10].sample(20)
df_char = df_char.loc[df_char['count'] >= 10]

In [23]:
exclude_chars = ['\n', ' ', '\\', '°', '.', "'", '"', '-', '!', '-', ')', '(', ':', ';',
                ',', '\u200b', '️', '/', '\xa0', "?", "&", '’', '~', '+', '*', '%', '_', 
                 '#', '=', '@', ']', '[']

mask = df_char['char'].map(lambda x: not (x.isalnum() or str(x) in exclude_chars))
print(mask.head(10))

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
Name: char, dtype: bool


In [25]:
df_char_special = df_char.loc[mask]
print(df_char_special)

    char  count
54     👍   4783
58     😍   3053
65     😊   2280
70     ❤   1731
76     🏻   1207
..   ...    ...
268    🥴     10
269    ❌     10
270    👆     10
272    ‍     10
273    🤘     10

[162 rows x 2 columns]


In [29]:
def counting_char_with_sentiment(char, sentiment):
    return sum([char in review for review in list(train.loc[train['rating'] == sentiment]['review'])])

In [30]:
for i in range(1,6):
    df_char_special[f'rating_{i}'] = np.vectorize(counting_char_with_sentiment)(df_char_special['char'], i)
    

In [43]:
df_char_special.head(10).style.background_gradient(cmap = 'Greens')

In [77]:
rating_cols = [f'rating_{i}' for i in range(1,6)]
weighted_score = list(np.arange(-1,1.5,0.5))

print(rating_cols)
df_char_special['score'] = np.array([list(df_char_special[a] * b) for a,b in zip(rating_cols, weighted_score)]).sum(axis = 0) / df_char_special[rating_cols].sum(axis = 1)
df_char_special.sort_values(by = 'score', ascending = False).head(10)[['char','score'] + rating_cols].style.background_gradient(cmap = 'Greens')

['rating_1', 'rating_2', 'rating_3', 'rating_4', 'rating_5']


In [88]:
df_char_special.sort_values(by = 'score', ascending = True).head(10)[['char','score'] + rating_cols].style.background_gradient(cmap = 'Reds_r')

In [64]:
print(np.array([list(df_char_special[f'{i}']) for i in rating_cols]).sum(axis = 1))

[ 1725  1489  5182 10884 10764]


In [78]:
a = np.arange(24).reshape(2,3,4)
print(a)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [80]:
print(a.sum(axis = 2))   #ans =6
print(a.sum(axis = 1))  #ans =8
print(a.sum(axis = 0))   #ans =12


[[ 6 22 38]
 [54 70 86]]
[[12 15 18 21]
 [48 51 54 57]]
[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
